@MTGWantList_HostAddress = http://localhost:5249

### Import Foundations into the catalogue

POST http://localhost:5249/api/mtgjson/import/FDN

###
GET http://localhost:5249/api/catalogue/stats

###
GET http://localhost:5249/api/catalogue/card/Llanowar%20Elves

###
GET http://localhost:5249/api/mtgjson/sets

###