// <auto-generated />
using System;
using MTGWantList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTGWantList.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825150439_InitialCatalogue")]
    partial class InitialCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTGWantList.Models.Catalogue.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScryfallOracleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScryfallOracleId")
                        .IsUnique()
                        .HasFilter("\"ScryfallOracleId\" IS NOT NULL");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTGWantList.Models.Catalogue.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MtgJsonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MtgJsonCode")
                        .IsUnique();

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("MTGWantList.Models.Catalogue.Printing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("CardSetId")
                        .HasColumnType("integer");

                    b.Property<string>("CardmarketId")
                        .HasColumnType("text");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MtgJsonUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CardSetId");

                    b.HasIndex("MtgJsonUuid")
                        .IsUnique();

                    b.ToTable("Printings");
                });

            modelBuilder.Entity("MTGWantList.Models.Catalogue.PrintingVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MtgJsonUuid")
                        .HasColumnType("text");

                    b.Property<string>("MtgJsonVersionId")
                        .HasColumnType("text");

                    b.Property<int>("PrintingId")
                        .HasColumnType("integer");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrintingId", "Language", "Finish")
                        .IsUnique();

                    b.ToTable("PrintingVariants");
                });

            modelBuilder.Entity("MTGWantList.Models.Catalogue.Printing", b =>
                {
                    b.HasOne("MTGWantList.Models.Catalogue.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTGWantList.Models.Catalogue.CardSet", "CardSet")
                        .WithMany()
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardSet");
                });

            modelBuilder.Entity("MTGWantList.Models.Catalogue.PrintingVariant", b =>
                {
                    b.HasOne("MTGWantList.Models.Catalogue.Printing", "Printing")
                        .WithMany()
                        .HasForeignKey("PrintingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Printing");
                });
#pragma warning restore 612, 618
        }
    }
}
